### ISSUE TITLE
Fix go ux sdk iteration struct/interface generation

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/openapiart#115]
Generated go <components/schemas/name>Iter objects need to be prefixed with the parent container in order to prevent conflicts across other objects.

```yaml
FlowUpdate:
  properties:
    flows:
      $ref: /components/schemas/Flow
```
conflicts with
```yaml
Config:
  properties:
    flows:
      $ref: /components/schemas/Flow
```
Generator should output `FlowUpdateFlowsIter` and `ConfigFlowsIter`
