### ISSUE TITLE
ENUMs are displayed as numeric value in serialized output

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#127]
Performing a `ToYaml` on container with enum, I get following output:

```yaml
  tx_rx:
    choice: 1
    port:
      rx_name: p1
      tx_name: p3
```
