### ISSUE TITLE
Equality check and/or introspection of objects changes choice

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/openapiart#139]
The following sample code changes the choice.
Choice should only change on setattr not on getattr.

```python
tcp.dst_port.value = 80
# the following should throw an exception
if tcp.dst_port.values[0] == 0:
   pass
```

**Comment by alakendu** [comment]
No, we put it in a backlog.

**Comment by Vibaswan** [comment]
# Proposal

### Summary 
If a user tries to retrieve or set a choice, when a choice is already set, we would throw an exception. 
We would also provide a way to user so that they can unset the current choice and then set the choice according to their need.

### Explanation with examples

Lets take a `sample` data model for the explanation
```yml
sample:
    type: object
    properties:
        name:
            type: string
        choice:   
            type: string
            enum:
                str_val:
                    type: string
                num_val:
                    type: int
                str_vals:
                    type: array of string
        
```

Python code snippet:
```python
s = api.Sample()
s.name = "new_sample"

# choice set by user
s.str_val = "str1"

# If now user tries to access or set another choice , they will see exception
# Both of the below statements will result in an exception
# Cannot set/retrieve num_val, as str_val was already set earlier
s.num_val
s.num_val = 23
```
**Note:** We will follow the same principle in go, but as we may know that it is not recommended to raise a panic.
In this case we should be raising panic cause user should be notified right away, as the next commands may have dependency on it. 

### Way to Unset Choice

Now if the user wants to unset the choice, we have choice property exposed which can be used,
but as when setting choice attribute we set the choice implicitly, it makes sense we expose some methods which unsets the choice implicitly as well.

```python
# unset the choice in sample
s.unset()
# now user can set the choice the want 
s.num_val = 23
```
**Note:** The function to reset or unset the choice should be named properly.
If we name it just unset users may feel it unsets the whole sample object which include choice as well as the other attributes such as `name` in this case. Maybe we can have `reset_choice` or `clear_choice`

### Scope
1. Snappi
2. GoSnappi

### Cons
1. Its on the user now to explicitly set unset the choice if they want to change the choice
2. It will effect existing scripts which are overriding choices in their script.
