### ISSUE TITLE
MEaningful error should be thrown if a component contains a nested component

### ISSUE THREAD

**Issue by jkristia** [open-traffic-generator/openapiart#201]
**Version information**
0.1.16

**Describe the bug**
A cryptic exception is thrown if a components property is an component definition (type: 'object')

**To Reproduce**
```yaml
components:
  schemas:
    RootComponentWithNested:
      description: |-
        Nested Component is not supported and should throw a meaningful exception
      properties:
        name:
          type: string
        nested_component:
          type: object
          properties:
            name:
              type: string

```
