### ISSUE TITLE
Support type:string minLength/maxLength

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/openapiart#215]
**Version information**
v0.1.20

**Describe the bug**
- OpenAPI type string modifiers of minLength/maxLength are not supported in generated validation code.
- OpenAPI minimum/maximum modifiers are allowed for type: string

**To Reproduce**
```yaml
property:
  valid:
    type: string
    minLength: 0
    maxLength: 255
  invalid:
    type: string
    minimum: 0
    maximum: 255
```

**Expected behavior**
The valid property above should generate validation code for ux sdk libraries.
The invalid property above should be caught by the bundler and an error should be raised.

**Additional context**
`openapi 3.0 spec` - datatypes https://spec.openapis.org/oas/v3.1.0#data-types
`json spec` - minLength/maxLength https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.3.2
