### ISSUE TITLE
SetChoice for enum is not setting the defaults for enum properties

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/openapiart#216]
**Version information**
openapiart==0.1.21

**Describe the bug**
SetChoice for enum is not setting the defaults for enum properties

**To Reproduce**
For FObject the enums are ["f_a", "f_b"]
1) f_a has default type and value.
2) f_b also has default type and value.
If SetChoice is set as "f_a" the default type and value are being set but if SetChoice is set as "f_b" the default value for f_b is not set

working:
=====
```
func TestSample(t *testing.T) {
	api := openapiart.NewApi()
	config := api.NewPrefixConfig()
	config.SetA("asdf").SetB(12.2).SetC(1)
	config.RequiredObject().SetEA(1).SetEB(2)
	f := config.K().FObject()
	f.SetChoice("f_a")
	config.SetResponse(openapiart.PrefixConfigResponse.STATUS_200)
	config.K().FObject().FA()
	log.Print(config.ToJson())
}
```

Not working:
========
```
func TestSample(t *testing.T) {
	api := openapiart.NewApi()
	config := api.NewPrefixConfig()
	config.SetA("asdf").SetB(12.2).SetC(1)
	config.RequiredObject().SetEA(1).SetEB(2)
	f := config.K().FObject()
	f.SetChoice("f_b")
	config.SetResponse(openapiart.PrefixConfigResponse.STATUS_200)
	config.K().FObject().FB()
	log.Print(config.ToJson())
}
```

**Expected behavior**
default value for choice f_b also should be set

**Additional context**
```
FObject model for reference
    FObject:
      type: object
      properties:
        choice:
          type: string
          enum: [f_a, f_b]
          default: 'f_a'
        f_a:
          type: string
          default: 'some string'
        f_b:
          type: number
          format: double
          default: 3.0
```
