### ISSUE TITLE
Using properties with camel case quietly fails

### ISSUE THREAD

**Issue by thomas-am** [open-traffic-generator/openapiart#294]
**Version information**
0.1.24

**Describe the bug**
Using camel case for a property quietly doesn't work.
Instead of producing an error when generating python code, it fails when using grpc APIs (e.g. ParseDict) to marshal created objects into a GRPC message.

```
components:
  schemas:
    Thing:
      type: object
      properties:
        thingProperty:
```

Note that it works correctly when using `thing_property`.

**Expected behavior**
If camel case is not supported, a clear error message should be generated when running the openapiart tools in a non-confirming openapi definition.
Or alternatively, camel case should be supported.
