### ISSUE TITLE
bundler.py generates default and format for values with incorrect indentation

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#32]
should be

```yaml
        values:
          type: array
          items:
            type: string
          default:
          - 0.0.0.0
          format: ipv4
```

but currently generated

```yaml
        values:
          type: array
          items:
            type: string
            default:
            - 0.0.0.0
            format: ipv4
```
