### ISSUE TITLE
Maintain consistent .proto message field numbers

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/openapiart#343]
**Version information**
0.1.45

**Describe the bug**
Openapiart go generation has the possibility of changing the order of message field numbers which breaks backward compatibility when using the grpc transport.

**To Reproduce**
Using the existing OTG model generate a base proto.
Then add a new property object in the middle of a schema object's properties. 
Generate a new proto file.
Notice that the field number in the proto for the newly added property is using an existing field number from the previous proto.
This breaks message serialization when using grpc.

**Expected behavior**
Regardless of whether openapi property objects are added, deprecated and removed the generated .proto file MUST maintain consistent message field numbers from version to version.

Possible extensions that can be used by openapiart go generation are the following:
```yaml
x-proto-field:
  description: >-
    Use of this extension is constrained to openapi property objects.
    The value given to this extension will be the value of the proto message field number.
    Used by openapiart go generator to set the field number.
    The go generator MUST validate that all properties in components/schemas MUST have an x-proto-field extension.
    The values MUST be unique within an object.
    Once a value has been assigned it must not be changed after the openapi document is released.
  type: integer

x-proto-reserved-fields:
  description: >-
    Use of the extension is constrained to openapi schema objects.
    Used by openapiart go generator to generate reserved fields in message that no longer exist in the API.
    When properties are removed from the API this extension should be used to preserve the field
    number generation in the .proto file. 
    The removed field's x-proto-field number should be added to the values of this extension.
  type: array
  items:
    type: integer
```

**Comment by ashutshkumr** [comment]
![Capture](https://user-images.githubusercontent.com/37202563/173040661-d109a7ff-e318-4086-b07e-bfc5f2e1c3b7.PNG)

**Comment by ajbalogh** [comment]
I think one consistent approach should be used (explicit x-field-uid) instead of a mixed approach (explicit and implicit numbering).
The proposed housekeeping script to auto annotate existing yaml should be run against the entire repo as part of this effort. 
Then going forward openapiart should fail on any missing required x-field-uid.

**Comment by ajbalogh** [comment]
If a property is never removed (renamed) then x-proto-reserved-fields is not required.

**Comment by winstonliu1111** [comment]
say we have field X in version 1, and someone had used that field say like the following:

object.set_Z(123).set_X(678).set_Z("abc") using snappi at version 1..

What do we expect the above to behave in the following situations, what is the experience for the end user?

In version 100, field X is deprecated?
In version 200, field X is completely removed (annotated with the reserved extension with the id that was defined in version 1)?

just want us to think through the hypotheticals.

**Comment by ajbalogh** [comment]
For deprecated fields there should be no change in behavior other than a warning should be emitted.
For removed fields the test should error as the field doesn't exist. If this is unacceptable then no field can be removed, only deprecated.

**Comment by winstonliu1111** [comment]
> For deprecated fields there should be no change in behavior other than a warning should be emitted. For removed fields the test should error as the field doesn't exist. If this is unacceptable then no field can be removed, only deprecated.

does this imply that on any "remove" event (assuming we can group that into some kind of cadence events where all removes happen in some epoch), we need to signal a update in our semantic versioning's major version?  (breakage in backward compatibility of the SDK)?    It would be good to outline these rules, and establish the guidelines.

**Comment by winstonliu1111** [comment]
@lemoncrust @ankur-sheth , FYI.  it's probably time we should think through our semantic versioning, and how we manage that as well.

**Comment by alakendu** [comment]
Please consider these scenario to setting `x-field-uid`

- ` x-include` : Openapiart bundler is filling properties for ` x-include`.  
```yaml
// user defined yaml
components:
  schemas:
    Flow:
      x-include:
      - '../common/common.yaml#/components/schemas/Named.Object'
```
```yaml
// consolidate yaml
components:
  schemas:
    Flow:
      properties:
        name:
          description: |-
            Globally unique name of an object. It also serves as the primary key for arrays of objects.
          type: string
          pattern: ^[\sa-zA-Z0-9-_()><\[\]]+$
```
- `responses`: We are resolving those '$ref` as well as consolidate within .proto
```yaml
paths:
  /results/states:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../result/states.yaml#/components/schemas/States.Response'
        '400':
          $ref: '../result/request.yaml#/components/responses/BadRequest'
```
```proto
message GetStatesResponse {
  optional StatesResponse status_code_200 = 1;
  optional ResponseError status_code_400 = 2;
}
```

**Comment by alakendu** [comment]
This is one of the proposed solution to address x-include: 
- ‘x-include’ list should replace with:
```yaml
x-include:
  - $ref: '../common/common.yaml#/components/schemas/Named.Object'
    x-field-uids:
                 min: 1
                 max: 3
```
- ‘x-include’ properties should configure with ‘x-field-uid’ which within the range of main, max value.
- User should not use any value present within ‘x-field-uids’.

@ajbalogh  please review
