### ISSUE TITLE
Add Validations for GO SDK

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/openapiart#61]
### `Is your feature request related to a use case? Please describe.`
As a user I've created a go ux sdk object and want to be notified of any errors prior to submitting the object to the server.  I also don't want to have to write `if err != nil` on every `Set<fieldname>` line of code.

The OpenapiArt generator MUST generate a common validation scheme so that when a message is sent over a transport (grpc/http) there are no validation errors present in the message.

Validation errors are those fields that do not fall within the bounds of the supported OpenApi keywords of
- format (supported formats are `mac, ipv4, ipv6, hex`)
- minimum (may be present when type is number, integer)
- maximum (may be present type is number, integer)
- minItems (may be present when type is array)
- maxItems (may be present when type is array)

### `Describe the solution you'd like`
Two methods of determining if objects are valid.
One can be called explicitly by the user (this allows the same sdk to be used server side) while the other is called implictly by the rpc function.  

The following example contains:
- a schema
- go ux sdk generated validation code
- test case demonstrating the two methods of validation

Sample OpenApi schema
```yaml
components:
  schemas:      
    Sample:
      properties:
        mac_address:
          type: string
          format: mac
        ipv4_address:
          type: string
          format: ipv4
        min_max_value:
          type: integer
          minimum: 6
          maximum: 20
        min_max_list:
          type: array
          minItems: 8
          maxItems: 8
          items:
            type: integer
```

Sample test case demonstrating how compile time type check passes and run time validation check.
```go
api := NewApi()
sample := api.NewSample()

// the following would all pass compile time check
// any runtime validation that does not pass will be added to an 
// internal struct to be checked on any rpc call or by a Validate
// function that can be called at any time
sample.SetMacAddress("3434334") 
sample.SetIpvAddress("asdfasdf") 
sample.SetMinMaxValue(34343)
sample.SetMinMaxList([]int{1, 2, 3})

// validation check 1
// can be done by a user at any time 
// and the returned error would report the contents from
// all the Set<fieldname> functions above
if err := api.Validate(sample); err != nil {
    panic(err)
}

// validation check 2
// if no validation has been done
// it will be done automatically in the rpc function 
// and the returned error would report the contents from 
// all the Set<fieldname> functions above
// nothing will be sent over the transport
warnings, err := api.SetSample(sample)
if err != nil {
    panic(err)
}
```

### `Describe alternatives you've considered`
Have each `Set<fieldname>` function panic as the code is executed. This would require a user to continually follow a practice of code/run/code/run... to resolve validation errors when they can all be reported at the time of the rpc call or an explicit Validate function.
