### ISSUE TITLE
Slice types are not updated for PrefixConfig in generated go sdk

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/openapiart#73]
Slice types are not updated for PrefixConfig in generated go sdk

models:
```
        d_values:
          description: A list of enum values
          type: array
          items:
            type: string
            enum: [a, b, c]
```

Slice d_values obj is not added for PrefixConfig in generation
=======================================

```
func (obj *prefixConfig) C() int32 {
	return obj.obj.C
}

func (obj *prefixConfig) SetC(value int32) PrefixConfig {
	obj.obj.C = value
	return obj
}

func (obj *prefixConfig) E() EObject {
	if obj.obj.E == nil {
		obj.obj.E = &sanity.EObject{}
	}
	return &eObject{obj: obj.obj.E}

}

```
