### ISSUE TITLE
Generate go ux sdk enums

### ISSUE THREAD

**Issue by ajbalogh** [open-traffic-generator/openapiart#86]
Given the following yaml definition
```yaml
PrefixConfig:
  type: object
  properties:
    response:
      type: string
      enum: [status_200, status_400, status_500]
```
Go UX generator should produce the following wrapper
```go
type PrefixConfigResponseEnum string

var PrefixConfigResponse = struct {
	STATUS_200 PrefixConfigResponseEnum
	STATUS_400 PrefixConfigResponseEnum
	STATUS_500 PrefixConfigResponseEnum
}{
	STATUS_200: PrefixConfigResponseEnum("status_200"),
	STATUS_400: PrefixConfigResponseEnum("status_400"),
	STATUS_500: PrefixConfigResponseEnum("status_500"),
}

func (obj *prefixConfig) SetResponse(value PrefixConfigResponseEnum) PrefixConfig {
	obj.obj.Response = sanity.PrefixConfig_Response_Enum(sanity.PrefixConfig_Response_Enum_value[string(value)])
}

func (obj *prefixConfig) Response() PrefixConfigResponseEnum {
	return PrefixConfigResponseEnum(obj.obj.Response.Enum().String())
}
```
Which can be consumed in the following way
```go
NewApi().NewPrefixConfig().SetResponse(PrefixConfigResponse.STATUS_200)
```
