### ISSUE TITLE
List of enum values for a type array is not updated as the property for Schema(Prefix.Config) in generated go sdk

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/openapiart#93]
```
components:
  schemas:
    Prefix.Config:
      x-include:
      - '../common/common.yaml#/components/schemas/GlobalObject'
      required: [a, b, c]
      properties:
        a:
          description: |-
            Small single line description
          type: string
          default: asdf
        b:
          description: |-
            Longer multi-line description
            Second line is here
            Third line
          type: number
          format: float
          default: 65.0
        c:
          type: integer
          default: 33
        d_values:
          description: A list of enum values
          type: array
          items:
            type: string
            enum: [a, b, c]
```

A list of enum values is not generated in go sdk, but generated pb file has the property 
=========================================================
```
type PrefixConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A               string                      `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B               float32                     `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	C               int32                       `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	DValues         []PrefixConfig_DValues_Enum `protobuf:"varint,4,rep,packed,name=d_values,json=dValues,
```

Pointer:
=====
https://github.com/open-traffic-generator/openapiart/blob/main/openapiart/openapiartgo.py#L475

for d_values property_name the below condition is satisfied and the generation is skipped
```
if len(self._get_parser("$..enum").find(property_schema)) > 0:  # temporary
```
